# Basic site settings
title: Jacob Keller
email: kiwiaviation1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Electrical and Computer Engineering student at Franklin W. College of Engineering. Check out my projects and get in touch!
baseurl: ""
url: "https://kiwiaviation.github.io"
github_username: KiwiAviation

# Build settings
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
  - jekyll-seo-tag
theme_config:
  appearance: "dark"
  back_home_text: "home" 
  date_format: "%Y-%m-%d" 
  show_description: true 

